// src/utils/seedInternships.js
import { createInternship } from "@/services/internshipService";

// Sample internships data
const sampleInternships = [
  {
    title: "Frontend Developer",
    company: "TechCorp Solutions",
    category: "Technology",
    location: "Bangalore, India",
    duration: "4 weeks",
    type: "Full-time",
    salary: "stipend: ₹5000/month",
    description: "Looking for passionate frontend developers to build responsive web applications using React and modern CSS. You'll work with our team to create engaging user interfaces.",
    skills: ["React", "JavaScript", "CSS", "HTML"],
    posted: "2 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Backend Engineer",
    company: "CloudSync Inc",
    category: "Technology",
    location: "Pune, India",
    duration: "6 weeks",
    type: "Full-time",
    salary: "stipend: ₹6000/month",
    description: "Develop scalable backend services using Node.js and MongoDB. Work with REST APIs and microservices architecture. Great learning opportunity for your career.",
    skills: ["Node.js", "MongoDB", "REST APIs", "Express.js"],
    posted: "1 day ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "UI/UX Designer",
    company: "Creative Studios",
    category: "Design",
    location: "Mumbai, India",
    duration: "8 weeks",
    type: "Full-time",
    salary: "stipend: ₹4500/month",
    description: "Design beautiful and intuitive user interfaces for mobile and web applications. Work with design tools like Figma and Adobe XD. Collaborate with product teams.",
    skills: ["Figma", "UI Design", "UX Research", "Adobe XD"],
    posted: "3 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Data Analyst",
    company: "InsightHub Analytics",
    category: "Analytics",
    location: "Hyderabad, India",
    duration: "6 weeks",
    type: "Full-time",
    salary: "stipend: ₹5500/month",
    description: "Analyze business data and create actionable insights. Work with SQL, Python, and BI tools. Help senior analysts in data-driven decision making.",
    skills: ["SQL", "Python", "Data Visualization", "Excel"],
    posted: "4 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Marketing Coordinator",
    company: "BrandBoost Marketing",
    category: "Marketing",
    location: "Delhi, India",
    duration: "4 weeks",
    type: "Full-time",
    salary: "stipend: ₹4000/month",
    description: "Support marketing campaigns and social media strategies. Engage with audience and analyze marketing metrics. Learn digital marketing best practices.",
    skills: ["Social Media", "Marketing", "Content Writing", "Analytics"],
    posted: "5 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Content Writer",
    company: "ContentFlow Media",
    category: "Writing",
    location: "Remote",
    duration: "4 weeks",
    type: "Full-time",
    salary: "stipend: ₹3500/month",
    description: "Create engaging content for blogs, social media, and marketing materials. Research industry trends and write SEO-optimized articles.",
    skills: ["Content Writing", "SEO", "Copywriting", "Blogging"],
    posted: "2 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Full Stack Developer",
    company: "WebEase Technologies",
    category: "Technology",
    location: "Bangalore, India",
    duration: "12 weeks",
    type: "Full-time",
    salary: "stipend: ₹7000/month",
    description: "Build complete web applications from frontend to backend. Work with React, Node.js, and MongoDB. Gain hands-on experience in full-stack development.",
    skills: ["React", "Node.js", "MongoDB", "JavaScript", "REST APIs"],
    posted: "1 week ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Mobile app Developer",
    company: "AppVenture Labs",
    category: "Technology",
    location: "Pune, India",
    duration: "8 weeks",
    type: "Full-time",
    salary: "stipend: ₹6500/month",
    description: "Develop mobile applications for iOS and Android. Learn React Native and cross-platform development. Work on real-world projects with senior developers.",
    skills: ["React Native", "JavaScript", "Mobile Development", "Flutter"],
    posted: "3 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Business Analyst",
    company: "Enterprise Solutions Ltd",
    category: "Analytics",
    location: "Mumbai, India",
    duration: "6 weeks",
    type: "Full-time",
    salary: "stipend: ₹5000/month",
    description: "Analyze business requirements and help in process improvement. Work with stakeholders to gather and document specifications.",
    skills: ["Business Analysis", "SQL", "Tableau", "Documentation"],
    posted: "2 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Graphic Designer",
    company: "DesignHub Studio",
    category: "Design",
    location: "Bangalore, India",
    duration: "4 weeks",
    type: "Full-time",
    salary: "stipend: ₹4000/month",
    description: "Create visual designs for marketing materials, social media, and branding. Work with Adobe Creative Suite and design latest trends.",
    skills: ["Photoshop", "Illustrator", "Design", "Branding"],
    posted: "5 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "QA Tester",
    company: "QualityFirst Testing",
    category: "Technology",
    location: "Hyderabad, India",
    duration: "6 weeks",
    type: "Full-time",
    salary: "stipend: ₹4500/month",
    description: "Test software applications for bugs and quality assurance. Learn automation testing and manual testing techniques.",
    skills: ["Testing", "Selenium", "QA", "Bug Reporting"],
    posted: "4 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Social Media Manager",
    company: "SocialBuzz Agency",
    category: "Marketing",
    location: "Remote",
    duration: "4 weeks",
    type: "Full-time",
    salary: "stipend: ₹4200/month",
    description: "Manage social media accounts and create engaging content. Monitor trends and analyze engagement metrics. Build community online.",
    skills: ["Social Media", "Content Creation", "Community Management", "Analytics"],
    posted: "2 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Sales Executive",
    company: "SalesPro Ventures",
    category: "Sales",
    location: "Bangalore, India",
    duration: "4 weeks",
    type: "Full-time",
    salary: "stipend: ₹5000/month + Commission",
    description: "Develop sales strategies and build client relationships. Meet targets and work towards business growth. Learn sales techniques.",
    skills: ["Sales", "Communication", "CRM", "Negotiation"],
    posted: "1 week ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "DevOps Engineer",
    company: "InfraCloud Systems",
    category: "Technology",
    location: "Pune, India",
    duration: "8 weeks",
    type: "Full-time",
    salary: "stipend: ₹6800/month",
    description: "Learn cloud deployment and infrastructure management. Work with Docker, Kubernetes, and CI/CD pipelines. Enhance your DevOps skills.",
    skills: ["Docker", "Kubernetes", "AWS", "CI/CD"],
    posted: "3 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Machine Learning Intern",
    company: "AI Innovation Hub",
    category: "Technology",
    location: "Bangalore, India",
    duration: "12 weeks",
    type: "Full-time",
    salary: "stipend: ₹8000/month",
    description: "Build machine learning models and work on AI projects. Learn TensorFlow, PyTorch, and deep learning. Contribute to real-world ML solutions.",
    skills: ["Python", "Machine Learning", "TensorFlow", "Data Science"],
    posted: "2 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "HR Coordinator",
    company: "PeopleFirst HR",
    category: "Marketing",
    location: "Delhi, India",
    duration: "4 weeks",
    type: "Full-time",
    salary: "stipend: ₹3800/month",
    description: "Support HR operations and recruitment processes. Assist in employee engagement activities and administrative tasks.",
    skills: ["HR", "Recruitment", "Communication", "Administration"],
    posted: "5 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Web Developer (PHP)",
    company: "WebSoft Development",
    category: "Technology",
    location: "Pune, India",
    duration: "6 weeks",
    type: "Full-time",
    salary: "stipend: ₹5200/month",
    description: "Develop web applications using PHP and MySQL. Work with Laravel framework. Build scalable and maintainable web solutions.",
    skills: ["PHP", "MySQL", "Laravel", "HTML", "CSS"],
    posted: "3 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Product Manager ",
    company: "ProductVision Inc",
    category: "Marketing",
    location: "Mumbai, India",
    duration: "8 weeks",
    type: "Full-time",
    salary: "stipend: ₹6000/month",
    description: "Work on product strategy and roadmap. Gather user feedback and define product requirements. Learn product management best practices.",
    skills: ["Product Management", "Analytics", "Communication", "Strategy"],
    posted: "4 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Cybersecurity Analyst",
    company: "SecurityShield Pro",
    category: "Technology",
    location: "Hyderabad, India",
    duration: "8 weeks",
    type: "Full-time",
    salary: "stipend: ₹6500/month",
    description: "Analyze security threats and implement protection measures. Learn network security and ethical hacking basics.",
    skills: ["Cybersecurity", "Network Security", "Ethical Hacking", "Linux"],
    posted: "2 days ago",
    status: "approved",
    createdAt: new Date(),
  },
  {
    title: "Video Editor",
    company: "MediaPro Studios",
    category: "Design",
    location: "Remote",
    duration: "4 weeks",
    type: "Full-time",
    salary: "stipend: ₹4300/month",
    description: "Edit and produce video content for social media and marketing. Learn video production and motion graphics.",
    skills: ["Video Editing", "Premiere Pro", "After Effects", "Motion Graphics"],
    posted: "5 days ago",
    status: "approved",
    createdAt: new Date(),
  },
];

/**
 * Seed internships to Firebase
 */
export const seedInternships = async () => {
  try {
    console.log("Starting to seed internships...");
    for (const internship of sampleInternships) {
      await createInternship(internship);
      console.log(`✓ Added: ${internship.title}`);
    }
    console.log("✓ All internships added successfully!");
    alert(`✓ Successfully added ${sampleInternships.length} internships to the database!`);
  } catch (error) {
    console.error("Error seeding internships:", error);
    alert("Error adding internships: " + error.message);
  }
};

export default sampleInternships;
